version: 2

models:
  - name: my_first_dbt_model
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
      - name: "second column"
        description: "The second column with a space in the name"
        tests:
          - unique
          - not_null
