default:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: {{ env_var('SNOWFLAKE_ACCOUNT') }}
      role: PUBLIC

      # User/password auth
      user: fokko
      password: {{ env_var('SNOWFLAKE_PASSWORD') }}

      database: INTEGRATION
      warehouse: INTEGRATION
      schema: INTEGRATION
      threads: 1