default:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"

      # User/password auth
      user: fokko
      password: "{{ env_var('SNOWFLAKE_PASSWORD') | as_text }}"

      role: PUBLIC
      database: "{{ env_var('SNOWFLAKE_DATABASE') | as_text }}"
      warehouse: INTEGRATION
      schema: INTEGRATION
      threads: 1
