name: DBT PR build

on:
  pull_request:

jobs:
  dbt:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    strategy:
      matrix:
        python-version: [ 3.8 ]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: pwd
        run: echo `pwd`

      - name: install deps
        run: python -m pip install dbt datafold-sdk

      - name: run dbt
        run: dbt run --profiles-dir /home/runner/work/dbt-snowflake/dbt-snowflake/

      - name: submit artifacts to datafold
        run: datafold dbt upload --ci-config-id 1 --run-type=pull_request --target-folder ./target/