name: DBT prod build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'


jobs:
  dbt:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    strategy:
      matrix:
        python-version: [ 3.8 ]

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: pwd
        run: echo `pwd`

      - name: install deps
        run: python -m pip install dbt datafold-sdk

      - name: run dbt
        run: dbt run --profiles-dir /home/runner/work/dbt-snowflake/dbt-snowflake/
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}

      - name: submit artifacts to datafold
        run: |
          datafold dbt upload --ci-config-id 1 --run-type=production --target-folder ./target/
        env:
          DATAFOLD_APIKEY: ${{ secrets.DATAFOLD_APIKEY }}